### ISSUE TITLE
Use `arc5gl` script from within environment, not hardwired to /proj/sot/ska

### ISSUE THREAD

**Issue by taldcroft** [sot/Ska.arc5gl#3]
Not an immediate priority, but this is a hidden dependency on legacy Ska for Ska3.

**Comment by jeanconn** [comment]
Though since arc5gl is only going to work from HEAD anyway, it may not matter if we call the Ska2 version of arc5gl in /proj/sot/ska/bin or test and configure a Ska3 version to run in the local environment.

**Comment by taldcroft** [comment]
Agreed, but calling a script in legacy Ska is contrary to the ideal of Ska3.  And as you discovered it can even be a problem in practice for testing.

**Comment by jeanconn** [comment]
Well, testing of arc5gl itself.  Hopefully arc5gl won't be a big deal to port to newer Perl.
